// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: proto/bff/moderation/v1/moderation_service.proto

package moderationv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{1}
}

type CandidateActor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did      string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	IsHidden bool   `protobuf:"varint,2,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	IsNsfw   bool   `protobuf:"varint,3,opt,name=is_nsfw,json=isNsfw,proto3" json:"is_nsfw,omitempty"`
	IsArtist bool   `protobuf:"varint,4,opt,name=is_artist,json=isArtist,proto3" json:"is_artist,omitempty"`
	Comment  string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *CandidateActor) Reset() {
	*x = CandidateActor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidateActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateActor) ProtoMessage() {}

func (x *CandidateActor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateActor.ProtoReflect.Descriptor instead.
func (*CandidateActor) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{2}
}

func (x *CandidateActor) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *CandidateActor) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *CandidateActor) GetIsNsfw() bool {
	if x != nil {
		return x.IsNsfw
	}
	return false
}

func (x *CandidateActor) GetIsArtist() bool {
	if x != nil {
		return x.IsArtist
	}
	return false
}

func (x *CandidateActor) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type GetCandidateActorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *GetCandidateActorRequest) Reset() {
	*x = GetCandidateActorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandidateActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateActorRequest) ProtoMessage() {}

func (x *GetCandidateActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateActorRequest.ProtoReflect.Descriptor instead.
func (*GetCandidateActorRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCandidateActorRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type GetCandidateActorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CandidateActor *CandidateActor `protobuf:"bytes,1,opt,name=candidate_actor,json=candidateActor,proto3" json:"candidate_actor,omitempty"`
}

func (x *GetCandidateActorResponse) Reset() {
	*x = GetCandidateActorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCandidateActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateActorResponse) ProtoMessage() {}

func (x *GetCandidateActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateActorResponse.ProtoReflect.Descriptor instead.
func (*GetCandidateActorResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCandidateActorResponse) GetCandidateActor() *CandidateActor {
	if x != nil {
		return x.CandidateActor
	}
	return nil
}

type CandidatePost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri       string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	ActorDid  string                 `protobuf:"bytes,2,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IndexedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
	IsNsfw    bool                   `protobuf:"varint,5,opt,name=is_nsfw,json=isNsfw,proto3" json:"is_nsfw,omitempty"`
	IsHidden  bool                   `protobuf:"varint,6,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
}

func (x *CandidatePost) Reset() {
	*x = CandidatePost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandidatePost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidatePost) ProtoMessage() {}

func (x *CandidatePost) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidatePost.ProtoReflect.Descriptor instead.
func (*CandidatePost) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{5}
}

func (x *CandidatePost) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *CandidatePost) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *CandidatePost) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CandidatePost) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

func (x *CandidatePost) GetIsNsfw() bool {
	if x != nil {
		return x.IsNsfw
	}
	return false
}

func (x *CandidatePost) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

type ListCandidatePostsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorDid string `protobuf:"bytes,1,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
}

func (x *ListCandidatePostsRequest) Reset() {
	*x = ListCandidatePostsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCandidatePostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidatePostsRequest) ProtoMessage() {}

func (x *ListCandidatePostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidatePostsRequest.ProtoReflect.Descriptor instead.
func (*ListCandidatePostsRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListCandidatePostsRequest) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

type ListCandidatePostsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CandidatePosts []*CandidatePost `protobuf:"bytes,1,rep,name=candidate_posts,json=candidatePosts,proto3" json:"candidate_posts,omitempty"`
}

func (x *ListCandidatePostsResponse) Reset() {
	*x = ListCandidatePostsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCandidatePostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidatePostsResponse) ProtoMessage() {}

func (x *ListCandidatePostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidatePostsResponse.ProtoReflect.Descriptor instead.
func (*ListCandidatePostsResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListCandidatePostsResponse) GetCandidatePosts() []*CandidatePost {
	if x != nil {
		return x.CandidatePosts
	}
	return nil
}

type ListCandidateActorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCandidateActorsRequest) Reset() {
	*x = ListCandidateActorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCandidateActorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidateActorsRequest) ProtoMessage() {}

func (x *ListCandidateActorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidateActorsRequest.ProtoReflect.Descriptor instead.
func (*ListCandidateActorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{8}
}

type ListCandidateActorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCandidateActorsResponse) Reset() {
	*x = ListCandidateActorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCandidateActorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidateActorsResponse) ProtoMessage() {}

func (x *ListCandidateActorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidateActorsResponse.ProtoReflect.Descriptor instead.
func (*ListCandidateActorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{9}
}

type ListCandidateLikesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCandidateLikesRequest) Reset() {
	*x = ListCandidateLikesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCandidateLikesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidateLikesRequest) ProtoMessage() {}

func (x *ListCandidateLikesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidateLikesRequest.ProtoReflect.Descriptor instead.
func (*ListCandidateLikesRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{10}
}

type ListCandidateLikesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCandidateLikesResponse) Reset() {
	*x = ListCandidateLikesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCandidateLikesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidateLikesResponse) ProtoMessage() {}

func (x *ListCandidateLikesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidateLikesResponse.ProtoReflect.Descriptor instead.
func (*ListCandidateLikesResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{11}
}

type ListCandidateFollowsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCandidateFollowsRequest) Reset() {
	*x = ListCandidateFollowsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCandidateFollowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidateFollowsRequest) ProtoMessage() {}

func (x *ListCandidateFollowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidateFollowsRequest.ProtoReflect.Descriptor instead.
func (*ListCandidateFollowsRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{12}
}

type ListCandidateFollowsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListCandidateFollowsResponse) Reset() {
	*x = ListCandidateFollowsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCandidateFollowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCandidateFollowsResponse) ProtoMessage() {}

func (x *ListCandidateFollowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCandidateFollowsResponse.ProtoReflect.Descriptor instead.
func (*ListCandidateFollowsResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP(), []int{13}
}

var File_proto_bff_moderation_v1_moderation_service_proto protoreflect.FileDescriptor

var file_proto_bff_moderation_v1_moderation_service_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x66, 0x66, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x62, 0x66, 0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73,
	0x5f, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6e, 0x73,
	0x66, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4e, 0x73, 0x66, 0x77,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2c, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x64, 0x69, 0x64, 0x22, 0x67, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x5f,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x62, 0x66,
	0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0e,
	0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x22, 0xea,
	0x01, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x69, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x69, 0x64, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x65, 0x64, 0x41, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6e, 0x73, 0x66, 0x77,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4e, 0x73, 0x66, 0x77, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x22, 0x38, 0x0a, 0x19, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x5f, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x44, 0x69, 0x64, 0x22, 0x67, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x70, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62,
	0x66, 0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x0e,
	0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x22, 0x1c,
	0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a, 0x19, 0x4c,
	0x69, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61,
	0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xad, 0x05, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x49, 0x0a, 0x04, 0x50,
	0x69, 0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x70, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x2b, 0x2e, 0x62, 0x66,
	0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x76, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12,
	0x2d, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e,
	0x2e, 0x62, 0x66, 0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x73, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x12, 0x2c, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x6d, 0x6f, 0x64,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x73, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e,
	0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x2c, 0x2e, 0x62, 0x66,
	0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x62, 0x66, 0x66, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x79, 0x0a, 0x14, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x73, 0x12, 0x2e, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4e, 0x5a, 0x4c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x64, 0x65, 0x79, 0x6e, 0x65, 0x74, 0x2f, 0x62,
	0x73, 0x6b, 0x79, 0x2d, 0x66, 0x75, 0x72, 0x72, 0x79, 0x2d, 0x66, 0x65, 0x65, 0x64, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x66, 0x66, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x76, 0x31, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bff_moderation_v1_moderation_service_proto_rawDescOnce sync.Once
	file_proto_bff_moderation_v1_moderation_service_proto_rawDescData = file_proto_bff_moderation_v1_moderation_service_proto_rawDesc
)

func file_proto_bff_moderation_v1_moderation_service_proto_rawDescGZIP() []byte {
	file_proto_bff_moderation_v1_moderation_service_proto_rawDescOnce.Do(func() {
		file_proto_bff_moderation_v1_moderation_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bff_moderation_v1_moderation_service_proto_rawDescData)
	})
	return file_proto_bff_moderation_v1_moderation_service_proto_rawDescData
}

var file_proto_bff_moderation_v1_moderation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_bff_moderation_v1_moderation_service_proto_goTypes = []interface{}{
	(*PingRequest)(nil),                  // 0: bff.moderation.v1.PingRequest
	(*PingResponse)(nil),                 // 1: bff.moderation.v1.PingResponse
	(*CandidateActor)(nil),               // 2: bff.moderation.v1.CandidateActor
	(*GetCandidateActorRequest)(nil),     // 3: bff.moderation.v1.GetCandidateActorRequest
	(*GetCandidateActorResponse)(nil),    // 4: bff.moderation.v1.GetCandidateActorResponse
	(*CandidatePost)(nil),                // 5: bff.moderation.v1.CandidatePost
	(*ListCandidatePostsRequest)(nil),    // 6: bff.moderation.v1.ListCandidatePostsRequest
	(*ListCandidatePostsResponse)(nil),   // 7: bff.moderation.v1.ListCandidatePostsResponse
	(*ListCandidateActorsRequest)(nil),   // 8: bff.moderation.v1.ListCandidateActorsRequest
	(*ListCandidateActorsResponse)(nil),  // 9: bff.moderation.v1.ListCandidateActorsResponse
	(*ListCandidateLikesRequest)(nil),    // 10: bff.moderation.v1.ListCandidateLikesRequest
	(*ListCandidateLikesResponse)(nil),   // 11: bff.moderation.v1.ListCandidateLikesResponse
	(*ListCandidateFollowsRequest)(nil),  // 12: bff.moderation.v1.ListCandidateFollowsRequest
	(*ListCandidateFollowsResponse)(nil), // 13: bff.moderation.v1.ListCandidateFollowsResponse
	(*timestamppb.Timestamp)(nil),        // 14: google.protobuf.Timestamp
}
var file_proto_bff_moderation_v1_moderation_service_proto_depIdxs = []int32{
	2,  // 0: bff.moderation.v1.GetCandidateActorResponse.candidate_actor:type_name -> bff.moderation.v1.CandidateActor
	14, // 1: bff.moderation.v1.CandidatePost.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: bff.moderation.v1.CandidatePost.indexed_at:type_name -> google.protobuf.Timestamp
	5,  // 3: bff.moderation.v1.ListCandidatePostsResponse.candidate_posts:type_name -> bff.moderation.v1.CandidatePost
	0,  // 4: bff.moderation.v1.ModerationService.Ping:input_type -> bff.moderation.v1.PingRequest
	3,  // 5: bff.moderation.v1.ModerationService.GetCandidateActor:input_type -> bff.moderation.v1.GetCandidateActorRequest
	8,  // 6: bff.moderation.v1.ModerationService.ListCandidateActors:input_type -> bff.moderation.v1.ListCandidateActorsRequest
	6,  // 7: bff.moderation.v1.ModerationService.ListCandidatePosts:input_type -> bff.moderation.v1.ListCandidatePostsRequest
	10, // 8: bff.moderation.v1.ModerationService.ListCandidateLikes:input_type -> bff.moderation.v1.ListCandidateLikesRequest
	12, // 9: bff.moderation.v1.ModerationService.ListCandidateFollows:input_type -> bff.moderation.v1.ListCandidateFollowsRequest
	1,  // 10: bff.moderation.v1.ModerationService.Ping:output_type -> bff.moderation.v1.PingResponse
	4,  // 11: bff.moderation.v1.ModerationService.GetCandidateActor:output_type -> bff.moderation.v1.GetCandidateActorResponse
	9,  // 12: bff.moderation.v1.ModerationService.ListCandidateActors:output_type -> bff.moderation.v1.ListCandidateActorsResponse
	7,  // 13: bff.moderation.v1.ModerationService.ListCandidatePosts:output_type -> bff.moderation.v1.ListCandidatePostsResponse
	11, // 14: bff.moderation.v1.ModerationService.ListCandidateLikes:output_type -> bff.moderation.v1.ListCandidateLikesResponse
	13, // 15: bff.moderation.v1.ModerationService.ListCandidateFollows:output_type -> bff.moderation.v1.ListCandidateFollowsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_bff_moderation_v1_moderation_service_proto_init() }
func file_proto_bff_moderation_v1_moderation_service_proto_init() {
	if File_proto_bff_moderation_v1_moderation_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CandidateActor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandidateActorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCandidateActorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CandidatePost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCandidatePostsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCandidatePostsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCandidateActorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCandidateActorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCandidateLikesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCandidateLikesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCandidateFollowsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_moderation_v1_moderation_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCandidateFollowsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bff_moderation_v1_moderation_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bff_moderation_v1_moderation_service_proto_goTypes,
		DependencyIndexes: file_proto_bff_moderation_v1_moderation_service_proto_depIdxs,
		MessageInfos:      file_proto_bff_moderation_v1_moderation_service_proto_msgTypes,
	}.Build()
	File_proto_bff_moderation_v1_moderation_service_proto = out.File
	file_proto_bff_moderation_v1_moderation_service_proto_rawDesc = nil
	file_proto_bff_moderation_v1_moderation_service_proto_goTypes = nil
	file_proto_bff_moderation_v1_moderation_service_proto_depIdxs = nil
}
