// @generated by protoc-gen-es v1.2.0 with parameter "target=js+dts"
// @generated from file proto/bff/moderation/v1/moderation_service.proto (package bff.moderation.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message bff.moderation.v1.PingRequest
 */
export const PingRequest = proto3.makeMessageType(
  "bff.moderation.v1.PingRequest",
  [],
);

/**
 * @generated from message bff.moderation.v1.PingResponse
 */
export const PingResponse = proto3.makeMessageType(
  "bff.moderation.v1.PingResponse",
  [],
);

/**
 * @generated from message bff.moderation.v1.CandidateActor
 */
export const CandidateActor = proto3.makeMessageType(
  "bff.moderation.v1.CandidateActor",
  () => [
    { no: 1, name: "did", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "is_hidden", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 3, name: "is_nsfw", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 4, name: "is_artist", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "comment", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message bff.moderation.v1.GetCandidateActorRequest
 */
export const GetCandidateActorRequest = proto3.makeMessageType(
  "bff.moderation.v1.GetCandidateActorRequest",
  () => [
    { no: 1, name: "did", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message bff.moderation.v1.GetCandidateActorResponse
 */
export const GetCandidateActorResponse = proto3.makeMessageType(
  "bff.moderation.v1.GetCandidateActorResponse",
  () => [
    { no: 1, name: "candidate_actor", kind: "message", T: CandidateActor },
  ],
);

/**
 * @generated from message bff.moderation.v1.CandidatePost
 */
export const CandidatePost = proto3.makeMessageType(
  "bff.moderation.v1.CandidatePost",
  () => [
    { no: 1, name: "uri", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "actor_did", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created_at", kind: "message", T: Timestamp },
    { no: 4, name: "indexed_at", kind: "message", T: Timestamp },
    { no: 5, name: "is_nsfw", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "is_hidden", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message bff.moderation.v1.ListCandidatePostsRequest
 */
export const ListCandidatePostsRequest = proto3.makeMessageType(
  "bff.moderation.v1.ListCandidatePostsRequest",
  () => [
    { no: 1, name: "actor_did", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message bff.moderation.v1.ListCandidatePostsResponse
 */
export const ListCandidatePostsResponse = proto3.makeMessageType(
  "bff.moderation.v1.ListCandidatePostsResponse",
  () => [
    { no: 1, name: "candidate_posts", kind: "message", T: CandidatePost, repeated: true },
  ],
);

/**
 * @generated from message bff.moderation.v1.ListCandidateActorsRequest
 */
export const ListCandidateActorsRequest = proto3.makeMessageType(
  "bff.moderation.v1.ListCandidateActorsRequest",
  [],
);

/**
 * @generated from message bff.moderation.v1.ListCandidateActorsResponse
 */
export const ListCandidateActorsResponse = proto3.makeMessageType(
  "bff.moderation.v1.ListCandidateActorsResponse",
  [],
);

/**
 * @generated from message bff.moderation.v1.ListCandidateLikesRequest
 */
export const ListCandidateLikesRequest = proto3.makeMessageType(
  "bff.moderation.v1.ListCandidateLikesRequest",
  [],
);

/**
 * @generated from message bff.moderation.v1.ListCandidateLikesResponse
 */
export const ListCandidateLikesResponse = proto3.makeMessageType(
  "bff.moderation.v1.ListCandidateLikesResponse",
  [],
);

/**
 * @generated from message bff.moderation.v1.ListCandidateFollowsRequest
 */
export const ListCandidateFollowsRequest = proto3.makeMessageType(
  "bff.moderation.v1.ListCandidateFollowsRequest",
  [],
);

/**
 * @generated from message bff.moderation.v1.ListCandidateFollowsResponse
 */
export const ListCandidateFollowsResponse = proto3.makeMessageType(
  "bff.moderation.v1.ListCandidateFollowsResponse",
  [],
);

