// @generated by protoc-gen-connect-web v0.9.0 with parameter "target=js+dts"
// @generated from file proto/bff/moderation/v1/moderation_service.proto (package bff.moderation.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetApprovalQueueRequest, GetApprovalQueueResponse, PingRequest, PingResponse, ProcessApprovalQueueRequest, ProcessApprovalQueueResponse } from "./moderation_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bff.moderation.v1.ModerationService
 */
export const ModerationService = {
  typeName: "bff.moderation.v1.ModerationService",
  methods: {
    /**
     * @generated from rpc bff.moderation.v1.ModerationService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.moderation.v1.ModerationService.GetApprovalQueue
     */
    getApprovalQueue: {
      name: "GetApprovalQueue",
      I: GetApprovalQueueRequest,
      O: GetApprovalQueueResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.moderation.v1.ModerationService.ProcessApprovalQueue
     */
    processApprovalQueue: {
      name: "ProcessApprovalQueue",
      I: ProcessApprovalQueueRequest,
      O: ProcessApprovalQueueResponse,
      kind: MethodKind.Unary,
    },
  }
};

