// @generated by protoc-gen-connect-web v0.9.0 with parameter "target=js+dts"
// @generated from file proto/bff/moderation/v1/moderation_service.proto (package bff.moderation.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetCandidateActorRequest, GetCandidateActorResponse, ListCandidateActorsRequest, ListCandidateActorsResponse, ListCandidateFollowsRequest, ListCandidateFollowsResponse, ListCandidateLikesRequest, ListCandidateLikesResponse, ListCandidatePostsRequest, ListCandidatePostsResponse, PingRequest, PingResponse } from "./moderation_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bff.moderation.v1.ModerationService
 */
export const ModerationService = {
  typeName: "bff.moderation.v1.ModerationService",
  methods: {
    /**
     * @generated from rpc bff.moderation.v1.ModerationService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.moderation.v1.ModerationService.GetCandidateActor
     */
    getCandidateActor: {
      name: "GetCandidateActor",
      I: GetCandidateActorRequest,
      O: GetCandidateActorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.moderation.v1.ModerationService.ListCandidateActors
     */
    listCandidateActors: {
      name: "ListCandidateActors",
      I: ListCandidateActorsRequest,
      O: ListCandidateActorsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.moderation.v1.ModerationService.ListCandidatePosts
     */
    listCandidatePosts: {
      name: "ListCandidatePosts",
      I: ListCandidatePostsRequest,
      O: ListCandidatePostsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.moderation.v1.ModerationService.ListCandidateLikes
     */
    listCandidateLikes: {
      name: "ListCandidateLikes",
      I: ListCandidateLikesRequest,
      O: ListCandidateLikesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.moderation.v1.ModerationService.ListCandidateFollows
     */
    listCandidateFollows: {
      name: "ListCandidateFollows",
      I: ListCandidateFollowsRequest,
      O: ListCandidateFollowsResponse,
      kind: MethodKind.Unary,
    },
  }
};

