// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: candidate_likes.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCandidateLike = `-- name: CreateCandidateLike :exec
INSERT INTO candidate_likes (
uri, repository_did, subject_uri, created_at, indexed_at
) VALUES (
$1, $2, $3, $4, $5
)
`

type CreateCandidateLikeParams struct {
	URI           string
	RepositoryDID string
	SubjectUri    string
	CreatedAt     pgtype.Timestamptz
	IndexedAt     pgtype.Timestamptz
}

func (q *Queries) CreateCandidateLike(ctx context.Context, arg CreateCandidateLikeParams) error {
	_, err := q.db.Exec(ctx, createCandidateLike,
		arg.URI,
		arg.RepositoryDID,
		arg.SubjectUri,
		arg.CreatedAt,
		arg.IndexedAt,
	)
	return err
}
