// @generated by protoc-gen-es v1.2.0 with parameter "target=js+dts"
// @generated from file proto/bff/moderation/v1/moderation_service.proto (package bff.moderation.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum bff.moderation.v1.ApprovalQueueAction
 */
export declare enum ApprovalQueueAction {
  /**
   * @generated from enum value: APPROVAL_QUEUE_ACTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: APPROVAL_QUEUE_ACTION_APPROVE = 1;
   */
  APPROVE = 1,

  /**
   * @generated from enum value: APPROVAL_QUEUE_ACTION_REJECT = 2;
   */
  REJECT = 2,
}

/**
 * @generated from message bff.moderation.v1.PingRequest
 */
export declare class PingRequest extends Message<PingRequest> {
  constructor(data?: PartialMessage<PingRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "bff.moderation.v1.PingRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PingRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PingRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PingRequest;

  static equals(a: PingRequest | PlainMessage<PingRequest> | undefined, b: PingRequest | PlainMessage<PingRequest> | undefined): boolean;
}

/**
 * @generated from message bff.moderation.v1.PingResponse
 */
export declare class PingResponse extends Message<PingResponse> {
  constructor(data?: PartialMessage<PingResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "bff.moderation.v1.PingResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PingResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PingResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PingResponse;

  static equals(a: PingResponse | PlainMessage<PingResponse> | undefined, b: PingResponse | PlainMessage<PingResponse> | undefined): boolean;
}

/**
 * @generated from message bff.moderation.v1.CandidateActor
 */
export declare class CandidateActor extends Message<CandidateActor> {
  /**
   * @generated from field: string did = 1;
   */
  did: string;

  /**
   * @generated from field: bool is_hidden = 2;
   */
  isHidden: boolean;

  /**
   * @generated from field: bool is_artist = 3;
   */
  isArtist: boolean;

  /**
   * @generated from field: string comment = 4;
   */
  comment: string;

  constructor(data?: PartialMessage<CandidateActor>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "bff.moderation.v1.CandidateActor";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CandidateActor;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CandidateActor;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CandidateActor;

  static equals(a: CandidateActor | PlainMessage<CandidateActor> | undefined, b: CandidateActor | PlainMessage<CandidateActor> | undefined): boolean;
}

/**
 * @generated from message bff.moderation.v1.GetApprovalQueueRequest
 */
export declare class GetApprovalQueueRequest extends Message<GetApprovalQueueRequest> {
  constructor(data?: PartialMessage<GetApprovalQueueRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "bff.moderation.v1.GetApprovalQueueRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetApprovalQueueRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetApprovalQueueRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetApprovalQueueRequest;

  static equals(a: GetApprovalQueueRequest | PlainMessage<GetApprovalQueueRequest> | undefined, b: GetApprovalQueueRequest | PlainMessage<GetApprovalQueueRequest> | undefined): boolean;
}

/**
 * @generated from message bff.moderation.v1.GetApprovalQueueResponse
 */
export declare class GetApprovalQueueResponse extends Message<GetApprovalQueueResponse> {
  /**
   * queue_entry is the candidate actor that needs to be processed by a mod.
   * process the queue entry using the ProcessApprovalQueueEntry RPC.
   *
   * @generated from field: bff.moderation.v1.CandidateActor queue_entry = 1;
   */
  queueEntry?: CandidateActor;

  /**
   * queue_entries_remaining indicates how many queue entries are left including
   * the one returned in this response.
   *
   * @generated from field: int32 queue_entries_remaining = 2;
   */
  queueEntriesRemaining: number;

  constructor(data?: PartialMessage<GetApprovalQueueResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "bff.moderation.v1.GetApprovalQueueResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetApprovalQueueResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetApprovalQueueResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetApprovalQueueResponse;

  static equals(a: GetApprovalQueueResponse | PlainMessage<GetApprovalQueueResponse> | undefined, b: GetApprovalQueueResponse | PlainMessage<GetApprovalQueueResponse> | undefined): boolean;
}

/**
 * @generated from message bff.moderation.v1.ProcessApprovalQueueRequest
 */
export declare class ProcessApprovalQueueRequest extends Message<ProcessApprovalQueueRequest> {
  /**
   * @generated from field: string did = 1;
   */
  did: string;

  /**
   * @generated from field: bff.moderation.v1.ApprovalQueueAction action = 2;
   */
  action: ApprovalQueueAction;

  /**
   * @generated from field: bool is_artist = 3;
   */
  isArtist: boolean;

  constructor(data?: PartialMessage<ProcessApprovalQueueRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "bff.moderation.v1.ProcessApprovalQueueRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProcessApprovalQueueRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProcessApprovalQueueRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProcessApprovalQueueRequest;

  static equals(a: ProcessApprovalQueueRequest | PlainMessage<ProcessApprovalQueueRequest> | undefined, b: ProcessApprovalQueueRequest | PlainMessage<ProcessApprovalQueueRequest> | undefined): boolean;
}

/**
 * @generated from message bff.moderation.v1.ProcessApprovalQueueResponse
 */
export declare class ProcessApprovalQueueResponse extends Message<ProcessApprovalQueueResponse> {
  constructor(data?: PartialMessage<ProcessApprovalQueueResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "bff.moderation.v1.ProcessApprovalQueueResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ProcessApprovalQueueResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ProcessApprovalQueueResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ProcessApprovalQueueResponse;

  static equals(a: ProcessApprovalQueueResponse | PlainMessage<ProcessApprovalQueueResponse> | undefined, b: ProcessApprovalQueueResponse | PlainMessage<ProcessApprovalQueueResponse> | undefined): boolean;
}

