// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: bff/v1/user_service.proto

package bffv1pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/strideynet/bsky-furry-feed/proto/bff/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion0_1_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "bff.v1.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceGetMeProcedure is the fully-qualified name of the UserService's GetMe RPC.
	UserServiceGetMeProcedure = "/bff.v1.UserService/GetMe"
	// UserServiceJoinApprovalQueueProcedure is the fully-qualified name of the UserService's
	// JoinApprovalQueue RPC.
	UserServiceJoinApprovalQueueProcedure = "/bff.v1.UserService/JoinApprovalQueue"
)

// UserServiceClient is a client for the bff.v1.UserService service.
type UserServiceClient interface {
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	JoinApprovalQueue(context.Context, *connect.Request[v1.JoinApprovalQueueRequest]) (*connect.Response[v1.JoinApprovalQueueResponse], error)
}

// NewUserServiceClient constructs a client for the bff.v1.UserService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &userServiceClient{
		getMe: connect.NewClient[v1.GetMeRequest, v1.GetMeResponse](
			httpClient,
			baseURL+UserServiceGetMeProcedure,
			opts...,
		),
		joinApprovalQueue: connect.NewClient[v1.JoinApprovalQueueRequest, v1.JoinApprovalQueueResponse](
			httpClient,
			baseURL+UserServiceJoinApprovalQueueProcedure,
			opts...,
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	getMe             *connect.Client[v1.GetMeRequest, v1.GetMeResponse]
	joinApprovalQueue *connect.Client[v1.JoinApprovalQueueRequest, v1.JoinApprovalQueueResponse]
}

// GetMe calls bff.v1.UserService.GetMe.
func (c *userServiceClient) GetMe(ctx context.Context, req *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return c.getMe.CallUnary(ctx, req)
}

// JoinApprovalQueue calls bff.v1.UserService.JoinApprovalQueue.
func (c *userServiceClient) JoinApprovalQueue(ctx context.Context, req *connect.Request[v1.JoinApprovalQueueRequest]) (*connect.Response[v1.JoinApprovalQueueResponse], error) {
	return c.joinApprovalQueue.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the bff.v1.UserService service.
type UserServiceHandler interface {
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	JoinApprovalQueue(context.Context, *connect.Request[v1.JoinApprovalQueueRequest]) (*connect.Response[v1.JoinApprovalQueueResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceGetMeHandler := connect.NewUnaryHandler(
		UserServiceGetMeProcedure,
		svc.GetMe,
		opts...,
	)
	userServiceJoinApprovalQueueHandler := connect.NewUnaryHandler(
		UserServiceJoinApprovalQueueProcedure,
		svc.JoinApprovalQueue,
		opts...,
	)
	return "/bff.v1.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceGetMeProcedure:
			userServiceGetMeHandler.ServeHTTP(w, r)
		case UserServiceJoinApprovalQueueProcedure:
			userServiceJoinApprovalQueueHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bff.v1.UserService.GetMe is not implemented"))
}

func (UnimplementedUserServiceHandler) JoinApprovalQueue(context.Context, *connect.Request[v1.JoinApprovalQueueRequest]) (*connect.Response[v1.JoinApprovalQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bff.v1.UserService.JoinApprovalQueue is not implemented"))
}
