// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: proto/bff/v1/moderation_service.proto

package bffv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorStatus int32

const (
	ActorStatus_ACTOR_STATUS_UNSPECIFIED ActorStatus = 0
	ActorStatus_ACTOR_STATUS_PENDING     ActorStatus = 1
	ActorStatus_ACTOR_STATUS_APPROVED    ActorStatus = 2
	ActorStatus_ACTOR_STATUS_BANNED      ActorStatus = 3
)

// Enum value maps for ActorStatus.
var (
	ActorStatus_name = map[int32]string{
		0: "ACTOR_STATUS_UNSPECIFIED",
		1: "ACTOR_STATUS_PENDING",
		2: "ACTOR_STATUS_APPROVED",
		3: "ACTOR_STATUS_BANNED",
	}
	ActorStatus_value = map[string]int32{
		"ACTOR_STATUS_UNSPECIFIED": 0,
		"ACTOR_STATUS_PENDING":     1,
		"ACTOR_STATUS_APPROVED":    2,
		"ACTOR_STATUS_BANNED":      3,
	}
)

func (x ActorStatus) Enum() *ActorStatus {
	p := new(ActorStatus)
	*p = x
	return p
}

func (x ActorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bff_v1_moderation_service_proto_enumTypes[0].Descriptor()
}

func (ActorStatus) Type() protoreflect.EnumType {
	return &file_proto_bff_v1_moderation_service_proto_enumTypes[0]
}

func (x ActorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActorStatus.Descriptor instead.
func (ActorStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{0}
}

type ApprovalQueueAction int32

const (
	ApprovalQueueAction_APPROVAL_QUEUE_ACTION_UNSPECIFIED ApprovalQueueAction = 0
	ApprovalQueueAction_APPROVAL_QUEUE_ACTION_APPROVE     ApprovalQueueAction = 1
	ApprovalQueueAction_APPROVAL_QUEUE_ACTION_REJECT      ApprovalQueueAction = 2
)

// Enum value maps for ApprovalQueueAction.
var (
	ApprovalQueueAction_name = map[int32]string{
		0: "APPROVAL_QUEUE_ACTION_UNSPECIFIED",
		1: "APPROVAL_QUEUE_ACTION_APPROVE",
		2: "APPROVAL_QUEUE_ACTION_REJECT",
	}
	ApprovalQueueAction_value = map[string]int32{
		"APPROVAL_QUEUE_ACTION_UNSPECIFIED": 0,
		"APPROVAL_QUEUE_ACTION_APPROVE":     1,
		"APPROVAL_QUEUE_ACTION_REJECT":      2,
	}
)

func (x ApprovalQueueAction) Enum() *ApprovalQueueAction {
	p := new(ApprovalQueueAction)
	*p = x
	return p
}

func (x ApprovalQueueAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalQueueAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_bff_v1_moderation_service_proto_enumTypes[1].Descriptor()
}

func (ApprovalQueueAction) Type() protoreflect.EnumType {
	return &file_proto_bff_v1_moderation_service_proto_enumTypes[1]
}

func (x ApprovalQueueAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalQueueAction.Descriptor instead.
func (ApprovalQueueAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{1}
}

type Actor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// did is the decentralized identity of the actor. This is also the UID used
	// for fetching and mutating actors.
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	// is_hidden is a deprecated flag that used to hide accounts. This no longer
	// has any effect.
	// Deprecated: Use status.
	IsHidden bool `protobuf:"varint,2,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	// is_artist is a flag indicating this account is primarily an artist. It
	// does not currently control any feed placement.
	IsArtist bool `protobuf:"varint,3,opt,name=is_artist,json=isArtist,proto3" json:"is_artist,omitempty"`
	// comment is a short string that is applied to an account when it is added
	// to the system. This will eventually be replaced by a more powerful system.
	Comment string `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	// status indicates the actor's current status.
	Status ActorStatus `protobuf:"varint,5,opt,name=status,proto3,enum=bff.v1.ActorStatus" json:"status,omitempty"`
	// created_at indicates the time that the actor was first added to the bff
	// system - this does not necessarily indicate when they joined bluesky.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Actor) Reset() {
	*x = Actor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{0}
}

func (x *Actor) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *Actor) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *Actor) GetIsArtist() bool {
	if x != nil {
		return x.IsArtist
	}
	return false
}

func (x *Actor) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Actor) GetStatus() ActorStatus {
	if x != nil {
		return x.Status
	}
	return ActorStatus_ACTOR_STATUS_UNSPECIFIED
}

func (x *Actor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri       string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IndexedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
}

func (x *Post) Reset() {
	*x = Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{1}
}

func (x *Post) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

type GetActorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetActorRequest) Reset() {
	*x = GetActorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorRequest) ProtoMessage() {}

func (x *GetActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorRequest.ProtoReflect.Descriptor instead.
func (*GetActorRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{2}
}

type GetActorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor *Actor `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *GetActorResponse) Reset() {
	*x = GetActorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorResponse) ProtoMessage() {}

func (x *GetActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorResponse.ProtoReflect.Descriptor instead.
func (*GetActorResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ListActorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListActorsRequest) Reset() {
	*x = ListActorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListActorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsRequest) ProtoMessage() {}

func (x *ListActorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsRequest.ProtoReflect.Descriptor instead.
func (*ListActorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{4}
}

type ListActorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actors []*Actor `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
}

func (x *ListActorsResponse) Reset() {
	*x = ListActorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListActorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsResponse) ProtoMessage() {}

func (x *ListActorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsResponse.ProtoReflect.Descriptor instead.
func (*ListActorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListActorsResponse) GetActors() []*Actor {
	if x != nil {
		return x.Actors
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{6}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{7}
}

type GetApprovalQueueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetApprovalQueueRequest) Reset() {
	*x = GetApprovalQueueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApprovalQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApprovalQueueRequest) ProtoMessage() {}

func (x *GetApprovalQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApprovalQueueRequest.ProtoReflect.Descriptor instead.
func (*GetApprovalQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{8}
}

type GetApprovalQueueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// queue_entry is the actor that needs to be processed by a mod. process the
	// queue entry using the ProcessApprovalQueue RPC.
	QueueEntry *Actor `protobuf:"bytes,1,opt,name=queue_entry,json=queueEntry,proto3" json:"queue_entry,omitempty"`
	// queue_entries_remaining indicates how many queue entries are left including
	// the one returned in this response.
	QueueEntriesRemaining int32 `protobuf:"varint,2,opt,name=queue_entries_remaining,json=queueEntriesRemaining,proto3" json:"queue_entries_remaining,omitempty"`
}

func (x *GetApprovalQueueResponse) Reset() {
	*x = GetApprovalQueueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetApprovalQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApprovalQueueResponse) ProtoMessage() {}

func (x *GetApprovalQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApprovalQueueResponse.ProtoReflect.Descriptor instead.
func (*GetApprovalQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetApprovalQueueResponse) GetQueueEntry() *Actor {
	if x != nil {
		return x.QueueEntry
	}
	return nil
}

func (x *GetApprovalQueueResponse) GetQueueEntriesRemaining() int32 {
	if x != nil {
		return x.QueueEntriesRemaining
	}
	return 0
}

type ProcessApprovalQueueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did      string              `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Action   ApprovalQueueAction `protobuf:"varint,2,opt,name=action,proto3,enum=bff.v1.ApprovalQueueAction" json:"action,omitempty"`
	IsArtist bool                `protobuf:"varint,3,opt,name=is_artist,json=isArtist,proto3" json:"is_artist,omitempty"`
}

func (x *ProcessApprovalQueueRequest) Reset() {
	*x = ProcessApprovalQueueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessApprovalQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessApprovalQueueRequest) ProtoMessage() {}

func (x *ProcessApprovalQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessApprovalQueueRequest.ProtoReflect.Descriptor instead.
func (*ProcessApprovalQueueRequest) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{10}
}

func (x *ProcessApprovalQueueRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ProcessApprovalQueueRequest) GetAction() ApprovalQueueAction {
	if x != nil {
		return x.Action
	}
	return ApprovalQueueAction_APPROVAL_QUEUE_ACTION_UNSPECIFIED
}

func (x *ProcessApprovalQueueRequest) GetIsArtist() bool {
	if x != nil {
		return x.IsArtist
	}
	return false
}

type ProcessApprovalQueueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProcessApprovalQueueResponse) Reset() {
	*x = ProcessApprovalQueueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessApprovalQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessApprovalQueueResponse) ProtoMessage() {}

func (x *ProcessApprovalQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bff_v1_moderation_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessApprovalQueueResponse.ProtoReflect.Descriptor instead.
func (*ProcessApprovalQueueResponse) Descriptor() ([]byte, []int) {
	return file_proto_bff_v1_moderation_service_proto_rawDescGZIP(), []int{11}
}

var File_proto_bff_v1_moderation_service_proto protoreflect.FileDescriptor

var file_proto_bff_v1_moderation_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x66, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xd5, 0x01, 0x0a, 0x05, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x73, 0x5f, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f,
	0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x8e, 0x01, 0x0a, 0x04, 0x50, 0x6f, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x69, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39,
	0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x64, 0x41, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x23, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x05,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x82, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61,
	0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e,
	0x0a, 0x0b, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x36,
	0x0a, 0x17, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x5f,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x15, 0x71, 0x75, 0x65, 0x75, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x22, 0x81, 0x01, 0x0a, 0x1b, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a,
	0x09, 0x69, 0x73, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x69, 0x73, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x22, 0x1e, 0x0a, 0x1c, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x79, 0x0a, 0x0b, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x18, 0x41, 0x43, 0x54,
	0x4f, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x43, 0x54, 0x4f, 0x52,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10,
	0x01, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13,
	0x41, 0x43, 0x54, 0x4f, 0x52, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x42, 0x41, 0x4e,
	0x4e, 0x45, 0x44, 0x10, 0x03, 0x2a, 0x81, 0x01, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a,
	0x21, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x41, 0x4c, 0x5f, 0x51, 0x55, 0x45, 0x55, 0x45, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x41, 0x4c,
	0x5f, 0x51, 0x55, 0x45, 0x55, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x50,
	0x50, 0x52, 0x4f, 0x56, 0x45, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x41, 0x50, 0x50, 0x52, 0x4f,
	0x56, 0x41, 0x4c, 0x5f, 0x51, 0x55, 0x45, 0x55, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x02, 0x32, 0x8e, 0x03, 0x0a, 0x11, 0x4d, 0x6f,
	0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x33, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x13, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x62,
	0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x1f, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x62, 0x66, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a,
	0x14, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x23, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75,
	0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x62, 0x66, 0x66,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x45, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x12, 0x19, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x62, 0x66,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x17, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x64, 0x65, 0x79,
	0x6e, 0x65, 0x74, 0x2f, 0x62, 0x73, 0x6b, 0x79, 0x2d, 0x66, 0x75, 0x72, 0x72, 0x79, 0x2d, 0x66,
	0x65, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x66, 0x66, 0x2f, 0x76, 0x31,
	0x3b, 0x62, 0x66, 0x66, 0x76, 0x31, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bff_v1_moderation_service_proto_rawDescOnce sync.Once
	file_proto_bff_v1_moderation_service_proto_rawDescData = file_proto_bff_v1_moderation_service_proto_rawDesc
)

func file_proto_bff_v1_moderation_service_proto_rawDescGZIP() []byte {
	file_proto_bff_v1_moderation_service_proto_rawDescOnce.Do(func() {
		file_proto_bff_v1_moderation_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bff_v1_moderation_service_proto_rawDescData)
	})
	return file_proto_bff_v1_moderation_service_proto_rawDescData
}

var file_proto_bff_v1_moderation_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_bff_v1_moderation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_bff_v1_moderation_service_proto_goTypes = []interface{}{
	(ActorStatus)(0),                     // 0: bff.v1.ActorStatus
	(ApprovalQueueAction)(0),             // 1: bff.v1.ApprovalQueueAction
	(*Actor)(nil),                        // 2: bff.v1.Actor
	(*Post)(nil),                         // 3: bff.v1.Post
	(*GetActorRequest)(nil),              // 4: bff.v1.GetActorRequest
	(*GetActorResponse)(nil),             // 5: bff.v1.GetActorResponse
	(*ListActorsRequest)(nil),            // 6: bff.v1.ListActorsRequest
	(*ListActorsResponse)(nil),           // 7: bff.v1.ListActorsResponse
	(*PingRequest)(nil),                  // 8: bff.v1.PingRequest
	(*PingResponse)(nil),                 // 9: bff.v1.PingResponse
	(*GetApprovalQueueRequest)(nil),      // 10: bff.v1.GetApprovalQueueRequest
	(*GetApprovalQueueResponse)(nil),     // 11: bff.v1.GetApprovalQueueResponse
	(*ProcessApprovalQueueRequest)(nil),  // 12: bff.v1.ProcessApprovalQueueRequest
	(*ProcessApprovalQueueResponse)(nil), // 13: bff.v1.ProcessApprovalQueueResponse
	(*timestamppb.Timestamp)(nil),        // 14: google.protobuf.Timestamp
}
var file_proto_bff_v1_moderation_service_proto_depIdxs = []int32{
	0,  // 0: bff.v1.Actor.status:type_name -> bff.v1.ActorStatus
	14, // 1: bff.v1.Actor.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: bff.v1.Post.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: bff.v1.Post.indexed_at:type_name -> google.protobuf.Timestamp
	2,  // 4: bff.v1.GetActorResponse.actor:type_name -> bff.v1.Actor
	2,  // 5: bff.v1.ListActorsResponse.actors:type_name -> bff.v1.Actor
	2,  // 6: bff.v1.GetApprovalQueueResponse.queue_entry:type_name -> bff.v1.Actor
	1,  // 7: bff.v1.ProcessApprovalQueueRequest.action:type_name -> bff.v1.ApprovalQueueAction
	8,  // 8: bff.v1.ModerationService.Ping:input_type -> bff.v1.PingRequest
	10, // 9: bff.v1.ModerationService.GetApprovalQueue:input_type -> bff.v1.GetApprovalQueueRequest
	12, // 10: bff.v1.ModerationService.ProcessApprovalQueue:input_type -> bff.v1.ProcessApprovalQueueRequest
	6,  // 11: bff.v1.ModerationService.ListActors:input_type -> bff.v1.ListActorsRequest
	4,  // 12: bff.v1.ModerationService.GetActor:input_type -> bff.v1.GetActorRequest
	9,  // 13: bff.v1.ModerationService.Ping:output_type -> bff.v1.PingResponse
	11, // 14: bff.v1.ModerationService.GetApprovalQueue:output_type -> bff.v1.GetApprovalQueueResponse
	13, // 15: bff.v1.ModerationService.ProcessApprovalQueue:output_type -> bff.v1.ProcessApprovalQueueResponse
	7,  // 16: bff.v1.ModerationService.ListActors:output_type -> bff.v1.ListActorsResponse
	5,  // 17: bff.v1.ModerationService.GetActor:output_type -> bff.v1.GetActorResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_bff_v1_moderation_service_proto_init() }
func file_proto_bff_v1_moderation_service_proto_init() {
	if File_proto_bff_v1_moderation_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bff_v1_moderation_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Actor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_v1_moderation_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_v1_moderation_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_v1_moderation_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_v1_moderation_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListActorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_v1_moderation_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListActorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_v1_moderation_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_v1_moderation_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_v1_moderation_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApprovalQueueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_v1_moderation_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetApprovalQueueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_v1_moderation_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessApprovalQueueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bff_v1_moderation_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessApprovalQueueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bff_v1_moderation_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bff_v1_moderation_service_proto_goTypes,
		DependencyIndexes: file_proto_bff_v1_moderation_service_proto_depIdxs,
		EnumInfos:         file_proto_bff_v1_moderation_service_proto_enumTypes,
		MessageInfos:      file_proto_bff_v1_moderation_service_proto_msgTypes,
	}.Build()
	File_proto_bff_v1_moderation_service_proto = out.File
	file_proto_bff_v1_moderation_service_proto_rawDesc = nil
	file_proto_bff_v1_moderation_service_proto_goTypes = nil
	file_proto_bff_v1_moderation_service_proto_depIdxs = nil
}
