// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: bff/v1/moderation_service.proto

package bffv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApprovalQueueAction int32

const (
	ApprovalQueueAction_APPROVAL_QUEUE_ACTION_UNSPECIFIED ApprovalQueueAction = 0
	ApprovalQueueAction_APPROVAL_QUEUE_ACTION_APPROVE     ApprovalQueueAction = 1
	ApprovalQueueAction_APPROVAL_QUEUE_ACTION_REJECT      ApprovalQueueAction = 2
)

// Enum value maps for ApprovalQueueAction.
var (
	ApprovalQueueAction_name = map[int32]string{
		0: "APPROVAL_QUEUE_ACTION_UNSPECIFIED",
		1: "APPROVAL_QUEUE_ACTION_APPROVE",
		2: "APPROVAL_QUEUE_ACTION_REJECT",
	}
	ApprovalQueueAction_value = map[string]int32{
		"APPROVAL_QUEUE_ACTION_UNSPECIFIED": 0,
		"APPROVAL_QUEUE_ACTION_APPROVE":     1,
		"APPROVAL_QUEUE_ACTION_REJECT":      2,
	}
)

func (x ApprovalQueueAction) Enum() *ApprovalQueueAction {
	p := new(ApprovalQueueAction)
	*p = x
	return p
}

func (x ApprovalQueueAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApprovalQueueAction) Descriptor() protoreflect.EnumDescriptor {
	return file_bff_v1_moderation_service_proto_enumTypes[0].Descriptor()
}

func (ApprovalQueueAction) Type() protoreflect.EnumType {
	return &file_bff_v1_moderation_service_proto_enumTypes[0]
}

func (x ApprovalQueueAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApprovalQueueAction.Descriptor instead.
func (ApprovalQueueAction) EnumDescriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{0}
}

type Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri       string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IndexedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
}

func (x *Post) Reset() {
	*x = Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

type GetActorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *GetActorRequest) Reset() {
	*x = GetActorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorRequest) ProtoMessage() {}

func (x *GetActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorRequest.ProtoReflect.Descriptor instead.
func (*GetActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetActorRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type GetActorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor *Actor `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *GetActorResponse) Reset() {
	*x = GetActorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorResponse) ProtoMessage() {}

func (x *GetActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorResponse.ProtoReflect.Descriptor instead.
func (*GetActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ListActorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cursor       string      `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit        int32       `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	FilterStatus ActorStatus `protobuf:"varint,3,opt,name=filter_status,json=filterStatus,proto3,enum=bff.v1.ActorStatus" json:"filter_status,omitempty"`
}

func (x *ListActorsRequest) Reset() {
	*x = ListActorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListActorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsRequest) ProtoMessage() {}

func (x *ListActorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsRequest.ProtoReflect.Descriptor instead.
func (*ListActorsRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListActorsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListActorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListActorsRequest) GetFilterStatus() ActorStatus {
	if x != nil {
		return x.FilterStatus
	}
	return ActorStatus_ACTOR_STATUS_UNSPECIFIED
}

type ListActorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actors []*Actor `protobuf:"bytes,1,rep,name=actors,proto3" json:"actors,omitempty"`
	Cursor string   `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
}

func (x *ListActorsResponse) Reset() {
	*x = ListActorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListActorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActorsResponse) ProtoMessage() {}

func (x *ListActorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActorsResponse.ProtoReflect.Descriptor instead.
func (*ListActorsResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListActorsResponse) GetActors() []*Actor {
	if x != nil {
		return x.Actors
	}
	return nil
}

func (x *ListActorsResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{5}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{6}
}

type ProcessApprovalQueueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did      string              `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Action   ApprovalQueueAction `protobuf:"varint,2,opt,name=action,proto3,enum=bff.v1.ApprovalQueueAction" json:"action,omitempty"`
	IsArtist bool                `protobuf:"varint,3,opt,name=is_artist,json=isArtist,proto3" json:"is_artist,omitempty"`
	// reason is the reason that the actor was approved or rejected. This is
	// currently optional but will become required for rejections eventually.
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ProcessApprovalQueueRequest) Reset() {
	*x = ProcessApprovalQueueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessApprovalQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessApprovalQueueRequest) ProtoMessage() {}

func (x *ProcessApprovalQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessApprovalQueueRequest.ProtoReflect.Descriptor instead.
func (*ProcessApprovalQueueRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessApprovalQueueRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *ProcessApprovalQueueRequest) GetAction() ApprovalQueueAction {
	if x != nil {
		return x.Action
	}
	return ApprovalQueueAction_APPROVAL_QUEUE_ACTION_UNSPECIFIED
}

func (x *ProcessApprovalQueueRequest) GetIsArtist() bool {
	if x != nil {
		return x.IsArtist
	}
	return false
}

func (x *ProcessApprovalQueueRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ProcessApprovalQueueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProcessApprovalQueueResponse) Reset() {
	*x = ProcessApprovalQueueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessApprovalQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessApprovalQueueResponse) ProtoMessage() {}

func (x *ProcessApprovalQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessApprovalQueueResponse.ProtoReflect.Descriptor instead.
func (*ProcessApprovalQueueResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{8}
}

// ProcessApprovalQueueAuditPayload is the payload for the
// `process_approval_queue` audit event.
type ProcessApprovalQueueAuditPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action ApprovalQueueAction `protobuf:"varint,1,opt,name=action,proto3,enum=bff.v1.ApprovalQueueAction" json:"action,omitempty"`
	Reason string              `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ProcessApprovalQueueAuditPayload) Reset() {
	*x = ProcessApprovalQueueAuditPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessApprovalQueueAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessApprovalQueueAuditPayload) ProtoMessage() {}

func (x *ProcessApprovalQueueAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessApprovalQueueAuditPayload.ProtoReflect.Descriptor instead.
func (*ProcessApprovalQueueAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessApprovalQueueAuditPayload) GetAction() ApprovalQueueAction {
	if x != nil {
		return x.Action
	}
	return ApprovalQueueAction_APPROVAL_QUEUE_ACTION_UNSPECIFIED
}

func (x *ProcessApprovalQueueAuditPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HoldBackPendingActorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *HoldBackPendingActorRequest) Reset() {
	*x = HoldBackPendingActorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HoldBackPendingActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldBackPendingActorRequest) ProtoMessage() {}

func (x *HoldBackPendingActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldBackPendingActorRequest.ProtoReflect.Descriptor instead.
func (*HoldBackPendingActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{10}
}

func (x *HoldBackPendingActorRequest) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

type HoldBackPendingActorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HoldBackPendingActorResponse) Reset() {
	*x = HoldBackPendingActorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HoldBackPendingActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldBackPendingActorResponse) ProtoMessage() {}

func (x *HoldBackPendingActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldBackPendingActorResponse.ProtoReflect.Descriptor instead.
func (*HoldBackPendingActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{11}
}

type HoldBackPendingActorAuditPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HoldBackPendingActorAuditPayload) Reset() {
	*x = HoldBackPendingActorAuditPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HoldBackPendingActorAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HoldBackPendingActorAuditPayload) ProtoMessage() {}

func (x *HoldBackPendingActorAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HoldBackPendingActorAuditPayload.ProtoReflect.Descriptor instead.
func (*HoldBackPendingActorAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{12}
}

type ListAuditEventsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterActorDid         string `protobuf:"bytes,1,opt,name=filter_actor_did,json=filterActorDid,proto3" json:"filter_actor_did,omitempty"`
	FilterSubjectDid       string `protobuf:"bytes,2,opt,name=filter_subject_did,json=filterSubjectDid,proto3" json:"filter_subject_did,omitempty"`
	FilterSubjectRecordUri string `protobuf:"bytes,3,opt,name=filter_subject_record_uri,json=filterSubjectRecordUri,proto3" json:"filter_subject_record_uri,omitempty"`
	// limit specifies how many audit events to return. If unspecific, this
	// defaults to 100.
	Limit  uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor string `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
}

func (x *ListAuditEventsRequest) Reset() {
	*x = ListAuditEventsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAuditEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsRequest) ProtoMessage() {}

func (x *ListAuditEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsRequest.ProtoReflect.Descriptor instead.
func (*ListAuditEventsRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListAuditEventsRequest) GetFilterActorDid() string {
	if x != nil {
		return x.FilterActorDid
	}
	return ""
}

func (x *ListAuditEventsRequest) GetFilterSubjectDid() string {
	if x != nil {
		return x.FilterSubjectDid
	}
	return ""
}

func (x *ListAuditEventsRequest) GetFilterSubjectRecordUri() string {
	if x != nil {
		return x.FilterSubjectRecordUri
	}
	return ""
}

func (x *ListAuditEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAuditEventsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListAuditEventsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuditEvents []*AuditEvent `protobuf:"bytes,1,rep,name=audit_events,json=auditEvents,proto3" json:"audit_events,omitempty"`
	Cursor      string        `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
}

func (x *ListAuditEventsResponse) Reset() {
	*x = ListAuditEventsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAuditEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditEventsResponse) ProtoMessage() {}

func (x *ListAuditEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditEventsResponse.ProtoReflect.Descriptor instead.
func (*ListAuditEventsResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListAuditEventsResponse) GetAuditEvents() []*AuditEvent {
	if x != nil {
		return x.AuditEvents
	}
	return nil
}

func (x *ListAuditEventsResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type CreateCommentAuditEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubjectDid       string `protobuf:"bytes,1,opt,name=subject_did,json=subjectDid,proto3" json:"subject_did,omitempty"`
	SubjectRecordUri string `protobuf:"bytes,2,opt,name=subject_record_uri,json=subjectRecordUri,proto3" json:"subject_record_uri,omitempty"`
	Comment          string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *CreateCommentAuditEventRequest) Reset() {
	*x = CreateCommentAuditEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentAuditEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentAuditEventRequest) ProtoMessage() {}

func (x *CreateCommentAuditEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentAuditEventRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentAuditEventRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateCommentAuditEventRequest) GetSubjectDid() string {
	if x != nil {
		return x.SubjectDid
	}
	return ""
}

func (x *CreateCommentAuditEventRequest) GetSubjectRecordUri() string {
	if x != nil {
		return x.SubjectRecordUri
	}
	return ""
}

func (x *CreateCommentAuditEventRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateCommentAuditEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuditEvent *AuditEvent `protobuf:"bytes,1,opt,name=audit_event,json=auditEvent,proto3" json:"audit_event,omitempty"`
}

func (x *CreateCommentAuditEventResponse) Reset() {
	*x = CreateCommentAuditEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCommentAuditEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentAuditEventResponse) ProtoMessage() {}

func (x *CreateCommentAuditEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentAuditEventResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentAuditEventResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCommentAuditEventResponse) GetAuditEvent() *AuditEvent {
	if x != nil {
		return x.AuditEvent
	}
	return nil
}

// CommentAuditPayload is the payload for the `comment`audit event. This is
// empty, as the comment is actually held within `AuditEvent`
type CommentAuditPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Comment string `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *CommentAuditPayload) Reset() {
	*x = CommentAuditPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentAuditPayload) ProtoMessage() {}

func (x *CommentAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentAuditPayload.ProtoReflect.Descriptor instead.
func (*CommentAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{17}
}

func (x *CommentAuditPayload) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateActorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorDid string `protobuf:"bytes,1,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	Reason   string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CreateActorRequest) Reset() {
	*x = CreateActorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActorRequest) ProtoMessage() {}

func (x *CreateActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActorRequest.ProtoReflect.Descriptor instead.
func (*CreateActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{18}
}

func (x *CreateActorRequest) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *CreateActorRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CreateActorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor *Actor `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *CreateActorResponse) Reset() {
	*x = CreateActorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActorResponse) ProtoMessage() {}

func (x *CreateActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActorResponse.ProtoReflect.Descriptor instead.
func (*CreateActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{19}
}

func (x *CreateActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type CreateActorAuditPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CreateActorAuditPayload) Reset() {
	*x = CreateActorAuditPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateActorAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActorAuditPayload) ProtoMessage() {}

func (x *CreateActorAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActorAuditPayload.ProtoReflect.Descriptor instead.
func (*CreateActorAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{20}
}

func (x *CreateActorAuditPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnapproveActorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorDid string `protobuf:"bytes,1,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	Reason   string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *UnapproveActorRequest) Reset() {
	*x = UnapproveActorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnapproveActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnapproveActorRequest) ProtoMessage() {}

func (x *UnapproveActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnapproveActorRequest.ProtoReflect.Descriptor instead.
func (*UnapproveActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{21}
}

func (x *UnapproveActorRequest) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *UnapproveActorRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnapproveActorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor *Actor `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *UnapproveActorResponse) Reset() {
	*x = UnapproveActorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnapproveActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnapproveActorResponse) ProtoMessage() {}

func (x *UnapproveActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnapproveActorResponse.ProtoReflect.Descriptor instead.
func (*UnapproveActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{22}
}

func (x *UnapproveActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type UnapproveActorAuditPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *UnapproveActorAuditPayload) Reset() {
	*x = UnapproveActorAuditPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnapproveActorAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnapproveActorAuditPayload) ProtoMessage() {}

func (x *UnapproveActorAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnapproveActorAuditPayload.ProtoReflect.Descriptor instead.
func (*UnapproveActorAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{23}
}

func (x *UnapproveActorAuditPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ForceApproveActorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorDid string `protobuf:"bytes,1,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	Reason   string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ForceApproveActorRequest) Reset() {
	*x = ForceApproveActorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForceApproveActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceApproveActorRequest) ProtoMessage() {}

func (x *ForceApproveActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceApproveActorRequest.ProtoReflect.Descriptor instead.
func (*ForceApproveActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{24}
}

func (x *ForceApproveActorRequest) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *ForceApproveActorRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ForceApproveActorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor *Actor `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *ForceApproveActorResponse) Reset() {
	*x = ForceApproveActorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForceApproveActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceApproveActorResponse) ProtoMessage() {}

func (x *ForceApproveActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceApproveActorResponse.ProtoReflect.Descriptor instead.
func (*ForceApproveActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{25}
}

func (x *ForceApproveActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type ForceApproveActorAuditPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ForceApproveActorAuditPayload) Reset() {
	*x = ForceApproveActorAuditPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForceApproveActorAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceApproveActorAuditPayload) ProtoMessage() {}

func (x *ForceApproveActorAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceApproveActorAuditPayload.ProtoReflect.Descriptor instead.
func (*ForceApproveActorAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{26}
}

func (x *ForceApproveActorAuditPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanActorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorDid string `protobuf:"bytes,1,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	Reason   string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *BanActorRequest) Reset() {
	*x = BanActorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BanActorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanActorRequest) ProtoMessage() {}

func (x *BanActorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanActorRequest.ProtoReflect.Descriptor instead.
func (*BanActorRequest) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{27}
}

func (x *BanActorRequest) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *BanActorRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanActorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Actor *Actor `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *BanActorResponse) Reset() {
	*x = BanActorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BanActorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanActorResponse) ProtoMessage() {}

func (x *BanActorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanActorResponse.ProtoReflect.Descriptor instead.
func (*BanActorResponse) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{28}
}

func (x *BanActorResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type BanActorAuditPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *BanActorAuditPayload) Reset() {
	*x = BanActorAuditPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BanActorAuditPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanActorAuditPayload) ProtoMessage() {}

func (x *BanActorAuditPayload) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanActorAuditPayload.ProtoReflect.Descriptor instead.
func (*BanActorAuditPayload) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{29}
}

func (x *BanActorAuditPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AuditEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id is a unique identifier of this audit event.
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// actor_did is the DID of the actor whose action caused this audit event
	// to be emitted.
	ActorDid string `protobuf:"bytes,3,opt,name=actor_did,json=actorDid,proto3" json:"actor_did,omitempty"`
	// subject_did is the DID of the actor who the action was done to.
	SubjectDid string `protobuf:"bytes,4,opt,name=subject_did,json=subjectDid,proto3" json:"subject_did,omitempty"`
	// subject_record_uri is the optional AT URI of a specific ATProto record
	// that the action was taken against.
	SubjectRecordUri string     `protobuf:"bytes,5,opt,name=subject_record_uri,json=subjectRecordUri,proto3" json:"subject_record_uri,omitempty"`
	Payload          *anypb.Any `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bff_v1_moderation_service_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bff_v1_moderation_service_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_bff_v1_moderation_service_proto_rawDescGZIP(), []int{30}
}

func (x *AuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditEvent) GetActorDid() string {
	if x != nil {
		return x.ActorDid
	}
	return ""
}

func (x *AuditEvent) GetSubjectDid() string {
	if x != nil {
		return x.SubjectDid
	}
	return ""
}

func (x *AuditEvent) GetSubjectRecordUri() string {
	if x != nil {
		return x.SubjectRecordUri
	}
	return ""
}

func (x *AuditEvent) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_bff_v1_moderation_service_proto protoreflect.FileDescriptor

var file_bff_v1_moderation_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x62, 0x66, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x62, 0x66, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x04, 0x50, 0x6f,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x69, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x39, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x64, 0x41, 0x74, 0x22, 0x23, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22,
	0x37, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x7b, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x38, 0x0a, 0x0d, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x53, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x66,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x06, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x99, 0x01, 0x0a, 0x1b, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x12, 0x33, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x66,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x1e, 0x0a, 0x1c, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6f, 0x0a, 0x20, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x41, 0x75, 0x64,
	0x69, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x33, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x66, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x1b, 0x48, 0x6f, 0x6c, 0x64, 0x42, 0x61,
	0x63, 0x6b, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x64, 0x22, 0x1e, 0x0a, 0x1c, 0x48, 0x6f, 0x6c, 0x64, 0x42,
	0x61, 0x63, 0x6b, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x20, 0x48, 0x6f, 0x6c, 0x64, 0x42,
	0x61, 0x63, 0x6b, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x41,
	0x75, 0x64, 0x69, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xd9, 0x01, 0x0a, 0x16,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x75, 0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x5f, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x69, 0x64,
	0x12, 0x2c, 0x0a, 0x12, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x69, 0x64, 0x12, 0x39,
	0x0a, 0x19, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x16, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x55, 0x72, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0x68, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x75, 0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x61, 0x75,
	0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f,
	0x72, 0x22, 0x89, 0x01, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x41, 0x75, 0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f,
	0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x44, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x55, 0x72, 0x69, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x56, 0x0a,
	0x1f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x75,
	0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x33, 0x0a, 0x0b, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x75, 0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x74,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x2f, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x41, 0x75, 0x64, 0x69, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x49, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x3a, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x31, 0x0a,
	0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x75, 0x64, 0x69,
	0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0x4c, 0x0a, 0x15, 0x55, 0x6e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x5f, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x44, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x3d,
	0x0a, 0x16, 0x55, 0x6e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x34, 0x0a,
	0x1a, 0x55, 0x6e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x41,
	0x75, 0x64, 0x69, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x18, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x41, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x40, 0x0a, 0x19, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x23, 0x0a, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x37, 0x0a, 0x1d, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x41,
	0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x75, 0x64, 0x69, 0x74,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x46, 0x0a, 0x0f, 0x42, 0x61, 0x6e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x37, 0x0a, 0x10, 0x42, 0x61, 0x6e, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x66, 0x66,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x22, 0x2e, 0x0a, 0x14, 0x42, 0x61, 0x6e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x75, 0x64, 0x69,
	0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x22, 0xf3, 0x01, 0x0a, 0x0a, 0x41, 0x75, 0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x5f, 0x64, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x44, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x5f, 0x64, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x44, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x75, 0x72, 0x69, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x55, 0x72, 0x69, 0x12, 0x2e, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x81, 0x01, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25,
	0x0a, 0x21, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x41, 0x4c, 0x5f, 0x51, 0x55, 0x45, 0x55, 0x45,
	0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x41,
	0x4c, 0x5f, 0x51, 0x55, 0x45, 0x55, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41,
	0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x41, 0x50, 0x50, 0x52,
	0x4f, 0x56, 0x41, 0x4c, 0x5f, 0x51, 0x55, 0x45, 0x55, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x02, 0x32, 0x98, 0x07, 0x0a, 0x11, 0x4d,
	0x6f, 0x64, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x33, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x13, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x12, 0x23, 0x2e,
	0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x41, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x63, 0x0a, 0x14, 0x48, 0x6f,
	0x6c, 0x64, 0x42, 0x61, 0x63, 0x6b, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x23, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x6c, 0x64,
	0x42, 0x61, 0x63, 0x6b, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x6f, 0x6c, 0x64, 0x42, 0x61, 0x63, 0x6b, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x19, 0x2e,
	0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x17, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x62, 0x66,
	0x66, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x08, 0x42, 0x61, 0x6e, 0x41, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x17, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x6e,
	0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x62,
	0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x6e, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0e, 0x55, 0x6e, 0x61, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1d, 0x2e, 0x62, 0x66, 0x66,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x6e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x62, 0x66, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x6e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x11, 0x46,
	0x6f, 0x72, 0x63, 0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x20, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x41,
	0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x6f, 0x72, 0x63,
	0x65, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1a, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x54, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x75, 0x64, 0x69, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x75, 0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x75, 0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6c, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x64, 0x69, 0x74, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x26, 0x2e, 0x62, 0x66, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x64, 0x69, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x62, 0x66, 0x66,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x41, 0x75, 0x64, 0x69, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x64, 0x65, 0x79, 0x6e, 0x65, 0x74, 0x2f, 0x62,
	0x73, 0x6b, 0x79, 0x2d, 0x66, 0x75, 0x72, 0x72, 0x79, 0x2d, 0x66, 0x65, 0x65, 0x64, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x66, 0x66, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x66, 0x66, 0x76,
	0x31, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bff_v1_moderation_service_proto_rawDescOnce sync.Once
	file_bff_v1_moderation_service_proto_rawDescData = file_bff_v1_moderation_service_proto_rawDesc
)

func file_bff_v1_moderation_service_proto_rawDescGZIP() []byte {
	file_bff_v1_moderation_service_proto_rawDescOnce.Do(func() {
		file_bff_v1_moderation_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bff_v1_moderation_service_proto_rawDescData)
	})
	return file_bff_v1_moderation_service_proto_rawDescData
}

var file_bff_v1_moderation_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bff_v1_moderation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_bff_v1_moderation_service_proto_goTypes = []interface{}{
	(ApprovalQueueAction)(0),                 // 0: bff.v1.ApprovalQueueAction
	(*Post)(nil),                             // 1: bff.v1.Post
	(*GetActorRequest)(nil),                  // 2: bff.v1.GetActorRequest
	(*GetActorResponse)(nil),                 // 3: bff.v1.GetActorResponse
	(*ListActorsRequest)(nil),                // 4: bff.v1.ListActorsRequest
	(*ListActorsResponse)(nil),               // 5: bff.v1.ListActorsResponse
	(*PingRequest)(nil),                      // 6: bff.v1.PingRequest
	(*PingResponse)(nil),                     // 7: bff.v1.PingResponse
	(*ProcessApprovalQueueRequest)(nil),      // 8: bff.v1.ProcessApprovalQueueRequest
	(*ProcessApprovalQueueResponse)(nil),     // 9: bff.v1.ProcessApprovalQueueResponse
	(*ProcessApprovalQueueAuditPayload)(nil), // 10: bff.v1.ProcessApprovalQueueAuditPayload
	(*HoldBackPendingActorRequest)(nil),      // 11: bff.v1.HoldBackPendingActorRequest
	(*HoldBackPendingActorResponse)(nil),     // 12: bff.v1.HoldBackPendingActorResponse
	(*HoldBackPendingActorAuditPayload)(nil), // 13: bff.v1.HoldBackPendingActorAuditPayload
	(*ListAuditEventsRequest)(nil),           // 14: bff.v1.ListAuditEventsRequest
	(*ListAuditEventsResponse)(nil),          // 15: bff.v1.ListAuditEventsResponse
	(*CreateCommentAuditEventRequest)(nil),   // 16: bff.v1.CreateCommentAuditEventRequest
	(*CreateCommentAuditEventResponse)(nil),  // 17: bff.v1.CreateCommentAuditEventResponse
	(*CommentAuditPayload)(nil),              // 18: bff.v1.CommentAuditPayload
	(*CreateActorRequest)(nil),               // 19: bff.v1.CreateActorRequest
	(*CreateActorResponse)(nil),              // 20: bff.v1.CreateActorResponse
	(*CreateActorAuditPayload)(nil),          // 21: bff.v1.CreateActorAuditPayload
	(*UnapproveActorRequest)(nil),            // 22: bff.v1.UnapproveActorRequest
	(*UnapproveActorResponse)(nil),           // 23: bff.v1.UnapproveActorResponse
	(*UnapproveActorAuditPayload)(nil),       // 24: bff.v1.UnapproveActorAuditPayload
	(*ForceApproveActorRequest)(nil),         // 25: bff.v1.ForceApproveActorRequest
	(*ForceApproveActorResponse)(nil),        // 26: bff.v1.ForceApproveActorResponse
	(*ForceApproveActorAuditPayload)(nil),    // 27: bff.v1.ForceApproveActorAuditPayload
	(*BanActorRequest)(nil),                  // 28: bff.v1.BanActorRequest
	(*BanActorResponse)(nil),                 // 29: bff.v1.BanActorResponse
	(*BanActorAuditPayload)(nil),             // 30: bff.v1.BanActorAuditPayload
	(*AuditEvent)(nil),                       // 31: bff.v1.AuditEvent
	(*timestamppb.Timestamp)(nil),            // 32: google.protobuf.Timestamp
	(*Actor)(nil),                            // 33: bff.v1.Actor
	(ActorStatus)(0),                         // 34: bff.v1.ActorStatus
	(*anypb.Any)(nil),                        // 35: google.protobuf.Any
}
var file_bff_v1_moderation_service_proto_depIdxs = []int32{
	32, // 0: bff.v1.Post.created_at:type_name -> google.protobuf.Timestamp
	32, // 1: bff.v1.Post.indexed_at:type_name -> google.protobuf.Timestamp
	33, // 2: bff.v1.GetActorResponse.actor:type_name -> bff.v1.Actor
	34, // 3: bff.v1.ListActorsRequest.filter_status:type_name -> bff.v1.ActorStatus
	33, // 4: bff.v1.ListActorsResponse.actors:type_name -> bff.v1.Actor
	0,  // 5: bff.v1.ProcessApprovalQueueRequest.action:type_name -> bff.v1.ApprovalQueueAction
	0,  // 6: bff.v1.ProcessApprovalQueueAuditPayload.action:type_name -> bff.v1.ApprovalQueueAction
	31, // 7: bff.v1.ListAuditEventsResponse.audit_events:type_name -> bff.v1.AuditEvent
	31, // 8: bff.v1.CreateCommentAuditEventResponse.audit_event:type_name -> bff.v1.AuditEvent
	33, // 9: bff.v1.CreateActorResponse.actor:type_name -> bff.v1.Actor
	33, // 10: bff.v1.UnapproveActorResponse.actor:type_name -> bff.v1.Actor
	33, // 11: bff.v1.ForceApproveActorResponse.actor:type_name -> bff.v1.Actor
	33, // 12: bff.v1.BanActorResponse.actor:type_name -> bff.v1.Actor
	32, // 13: bff.v1.AuditEvent.created_at:type_name -> google.protobuf.Timestamp
	35, // 14: bff.v1.AuditEvent.payload:type_name -> google.protobuf.Any
	6,  // 15: bff.v1.ModerationService.Ping:input_type -> bff.v1.PingRequest
	8,  // 16: bff.v1.ModerationService.ProcessApprovalQueue:input_type -> bff.v1.ProcessApprovalQueueRequest
	11, // 17: bff.v1.ModerationService.HoldBackPendingActor:input_type -> bff.v1.HoldBackPendingActorRequest
	4,  // 18: bff.v1.ModerationService.ListActors:input_type -> bff.v1.ListActorsRequest
	2,  // 19: bff.v1.ModerationService.GetActor:input_type -> bff.v1.GetActorRequest
	28, // 20: bff.v1.ModerationService.BanActor:input_type -> bff.v1.BanActorRequest
	22, // 21: bff.v1.ModerationService.UnapproveActor:input_type -> bff.v1.UnapproveActorRequest
	25, // 22: bff.v1.ModerationService.ForceApproveActor:input_type -> bff.v1.ForceApproveActorRequest
	19, // 23: bff.v1.ModerationService.CreateActor:input_type -> bff.v1.CreateActorRequest
	14, // 24: bff.v1.ModerationService.ListAuditEvents:input_type -> bff.v1.ListAuditEventsRequest
	16, // 25: bff.v1.ModerationService.CreateCommentAuditEvent:input_type -> bff.v1.CreateCommentAuditEventRequest
	7,  // 26: bff.v1.ModerationService.Ping:output_type -> bff.v1.PingResponse
	9,  // 27: bff.v1.ModerationService.ProcessApprovalQueue:output_type -> bff.v1.ProcessApprovalQueueResponse
	12, // 28: bff.v1.ModerationService.HoldBackPendingActor:output_type -> bff.v1.HoldBackPendingActorResponse
	5,  // 29: bff.v1.ModerationService.ListActors:output_type -> bff.v1.ListActorsResponse
	3,  // 30: bff.v1.ModerationService.GetActor:output_type -> bff.v1.GetActorResponse
	29, // 31: bff.v1.ModerationService.BanActor:output_type -> bff.v1.BanActorResponse
	23, // 32: bff.v1.ModerationService.UnapproveActor:output_type -> bff.v1.UnapproveActorResponse
	26, // 33: bff.v1.ModerationService.ForceApproveActor:output_type -> bff.v1.ForceApproveActorResponse
	20, // 34: bff.v1.ModerationService.CreateActor:output_type -> bff.v1.CreateActorResponse
	15, // 35: bff.v1.ModerationService.ListAuditEvents:output_type -> bff.v1.ListAuditEventsResponse
	17, // 36: bff.v1.ModerationService.CreateCommentAuditEvent:output_type -> bff.v1.CreateCommentAuditEventResponse
	26, // [26:37] is the sub-list for method output_type
	15, // [15:26] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_bff_v1_moderation_service_proto_init() }
func file_bff_v1_moderation_service_proto_init() {
	if File_bff_v1_moderation_service_proto != nil {
		return
	}
	file_bff_v1_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bff_v1_moderation_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListActorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListActorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessApprovalQueueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessApprovalQueueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessApprovalQueueAuditPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HoldBackPendingActorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HoldBackPendingActorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HoldBackPendingActorAuditPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAuditEventsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAuditEventsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentAuditEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCommentAuditEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentAuditPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateActorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateActorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateActorAuditPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnapproveActorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnapproveActorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnapproveActorAuditPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForceApproveActorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForceApproveActorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForceApproveActorAuditPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BanActorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BanActorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BanActorAuditPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bff_v1_moderation_service_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuditEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bff_v1_moderation_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bff_v1_moderation_service_proto_goTypes,
		DependencyIndexes: file_bff_v1_moderation_service_proto_depIdxs,
		EnumInfos:         file_bff_v1_moderation_service_proto_enumTypes,
		MessageInfos:      file_bff_v1_moderation_service_proto_msgTypes,
	}.Build()
	File_bff_v1_moderation_service_proto = out.File
	file_bff_v1_moderation_service_proto_rawDesc = nil
	file_bff_v1_moderation_service_proto_goTypes = nil
	file_bff_v1_moderation_service_proto_depIdxs = nil
}
