// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=js+dts"
// @generated from file bff/v1/moderation_service.proto (package bff.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BanActorRequest, BanActorResponse, CreateActorRequest, CreateActorResponse, CreateCommentAuditEventRequest, CreateCommentAuditEventResponse, ForceApproveActorRequest, ForceApproveActorResponse, GetActorRequest, GetActorResponse, HoldBackPendingActorRequest, HoldBackPendingActorResponse, ListActorsRequest, ListActorsResponse, ListAuditEventsRequest, ListAuditEventsResponse, ListRolesRequest, ListRolesResponse, PingRequest, PingResponse, ProcessApprovalQueueRequest, ProcessApprovalQueueResponse, UnapproveActorRequest, UnapproveActorResponse } from "./moderation_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bff.v1.ModerationService
 */
export declare const ModerationService: {
  readonly typeName: "bff.v1.ModerationService",
  readonly methods: {
    /**
     * Ping is a test RPC that checks that the user is authenticated and then
     * returns an empty response. Ideal for health checking the moderation service.
     *
     * @generated from rpc bff.v1.ModerationService.Ping
     */
    readonly ping: {
      readonly name: "Ping",
      readonly I: typeof PingRequest,
      readonly O: typeof PingResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * TODO: Refactor ProcessApprovalQueue to something more like "ProcessPendingActor"
     *
     * @generated from rpc bff.v1.ModerationService.ProcessApprovalQueue
     */
    readonly processApprovalQueue: {
      readonly name: "ProcessApprovalQueue",
      readonly I: typeof ProcessApprovalQueueRequest,
      readonly O: typeof ProcessApprovalQueueResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * HoldBackPendingActor ignores a pending actor for review in some time, so we
     * don’t need to reject actors that e.g. have no avatar or bio yet.
     *
     * @generated from rpc bff.v1.ModerationService.HoldBackPendingActor
     */
    readonly holdBackPendingActor: {
      readonly name: "HoldBackPendingActor",
      readonly I: typeof HoldBackPendingActorRequest,
      readonly O: typeof HoldBackPendingActorResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ListActors fetches multiple actors from the database. It allows this to be
     * filtered by certain attributes.
     *
     * @generated from rpc bff.v1.ModerationService.ListActors
     */
    readonly listActors: {
      readonly name: "ListActors",
      readonly I: typeof ListActorsRequest,
      readonly O: typeof ListActorsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * GetActor fetches a single actor from the database.
     *
     * @generated from rpc bff.v1.ModerationService.GetActor
     */
    readonly getActor: {
      readonly name: "GetActor",
      readonly I: typeof GetActorRequest,
      readonly O: typeof GetActorResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * BanActor changes an actors status to "banned".
     * Actor can be in any status before they are banned.
     *
     * @generated from rpc bff.v1.ModerationService.BanActor
     */
    readonly banActor: {
      readonly name: "BanActor",
      readonly I: typeof BanActorRequest,
      readonly O: typeof BanActorResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * UnapproveActor changes an actor from "approved" status to "none" status.
     *
     * @generated from rpc bff.v1.ModerationService.UnapproveActor
     */
    readonly unapproveActor: {
      readonly name: "UnapproveActor",
      readonly I: typeof UnapproveActorRequest,
      readonly O: typeof UnapproveActorResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * ForceApproveActor changes an actor to "approved" status from "none" or "pending".
     *
     * @generated from rpc bff.v1.ModerationService.ForceApproveActor
     */
    readonly forceApproveActor: {
      readonly name: "ForceApproveActor",
      readonly I: typeof ForceApproveActorRequest,
      readonly O: typeof ForceApproveActorResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * CreateActor creates a database entry for an actor who does not currently exist.
     * By default, their status will be set to none.
     *
     * @generated from rpc bff.v1.ModerationService.CreateActor
     */
    readonly createActor: {
      readonly name: "CreateActor",
      readonly I: typeof CreateActorRequest,
      readonly O: typeof CreateActorResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.v1.ModerationService.ListAuditEvents
     */
    readonly listAuditEvents: {
      readonly name: "ListAuditEvents",
      readonly I: typeof ListAuditEventsRequest,
      readonly O: typeof ListAuditEventsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.v1.ModerationService.CreateCommentAuditEvent
     */
    readonly createCommentAuditEvent: {
      readonly name: "CreateCommentAuditEvent",
      readonly I: typeof CreateCommentAuditEventRequest,
      readonly O: typeof CreateCommentAuditEventResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.v1.ModerationService.ListRoles
     */
    readonly listRoles: {
      readonly name: "ListRoles",
      readonly I: typeof ListRolesRequest,
      readonly O: typeof ListRolesResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

