// @generated by protoc-gen-connect-web v0.9.0 with parameter "target=js+dts"
// @generated from file bff/v1/user_service.proto (package bff.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetMeRequest, GetMeResponse, JoinApprovalQueueRequest, JoinApprovalQueueResponse } from "./user_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bff.v1.UserService
 */
export const UserService = {
  typeName: "bff.v1.UserService",
  methods: {
    /**
     * @generated from rpc bff.v1.UserService.GetMe
     */
    getMe: {
      name: "GetMe",
      I: GetMeRequest,
      O: GetMeResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.v1.UserService.JoinApprovalQueue
     */
    joinApprovalQueue: {
      name: "JoinApprovalQueue",
      I: JoinApprovalQueueRequest,
      O: JoinApprovalQueueResponse,
      kind: MethodKind.Unary,
    },
  }
};

