// @generated by protoc-gen-es v1.3.3 with parameter "target=js+dts"
// @generated from file bff/v1/user_service.proto (package bff.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Actor } from "./types_pb.js";

/**
 * @generated from message bff.v1.GetMeRequest
 */
export const GetMeRequest = proto3.makeMessageType(
  "bff.v1.GetMeRequest",
  [],
);

/**
 * @generated from message bff.v1.GetMeResponse
 */
export const GetMeResponse = proto3.makeMessageType(
  "bff.v1.GetMeResponse",
  () => [
    { no: 1, name: "Actor", kind: "message", T: Actor },
  ],
);

/**
 * @generated from message bff.v1.JoinApprovalQueueRequest
 */
export const JoinApprovalQueueRequest = proto3.makeMessageType(
  "bff.v1.JoinApprovalQueueRequest",
  [],
);

/**
 * @generated from message bff.v1.JoinApprovalQueueResponse
 */
export const JoinApprovalQueueResponse = proto3.makeMessageType(
  "bff.v1.JoinApprovalQueueResponse",
  [],
);

