// @generated by protoc-gen-connect-web v0.11.0 with parameter "target=js+dts"
// @generated from file bff/v1/user_service.proto (package bff.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetMeRequest, GetMeResponse, JoinApprovalQueueRequest, JoinApprovalQueueResponse } from "./user_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service bff.v1.UserService
 */
export declare const UserService: {
  readonly typeName: "bff.v1.UserService",
  readonly methods: {
    /**
     * @generated from rpc bff.v1.UserService.GetMe
     */
    readonly getMe: {
      readonly name: "GetMe",
      readonly I: typeof GetMeRequest,
      readonly O: typeof GetMeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc bff.v1.UserService.JoinApprovalQueue
     */
    readonly joinApprovalQueue: {
      readonly name: "JoinApprovalQueue",
      readonly I: typeof JoinApprovalQueueRequest,
      readonly O: typeof JoinApprovalQueueResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

